# Site Information
site_name: The Thinking Lab
site_author: Hariprasad
site_description: A digital library
site_url: https://har1prasad.github.io/the-thinking-lab/


# Theme
theme:
  name: material

  # Fonts
  font:
    text: Lexend
    code: JetBrains Mono

  # Branding
  logo: assets/logo.png 
  favicon: assets/favicon.ico

  # Theme Features
  features:
    - content.code.copy
    - navigation.top        # back to top button, useful for long notes pages
    - search.suggest        # autocomplete in search
    # - navigation.footer

  # Color Palette
  palette:

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search

# Markdown Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - tables
  - pymdownx.blocks.caption

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # Not including in table of content
  - toc:
      toc_depth: 3

  # Emoji
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

  # Code Highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true

  # Advanced Code Blocks
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets

  # Tabs
  - pymdownx.tabbed:
      alternate_style: true

extra:
  social:
  # Social Links
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/hariprasad-ap/

    - icon: fontawesome/brands/github
      link: https://github.com/har1prasad

    - icon: fontawesome/brands/x-twitter
      link: https://x.com/Har1prasad

    - icon: simple/leetcode
      link: https://leetcode.com/u/har1prasad/
  
  analytics:
  # Google analytics
    provider: google
    property: G-Q2FM4EYKLD


# Extra CSS
extra_css:
  - stylesheets/extra.css

#navigation
nav:
  - Home: index.md
  - About Me: About-me.md
  - Notes:
    - Python:
      - Introduction: notes/python/python-introduction.md
      - Variables & data types: notes/python/python-variables.md
      - Strings: notes/python/python-string.md
      - Comparisons: notes/python/python-comparisons.md
      - Loops: notes/python/python-loops.md
      - Lists: notes/python/python-list.md
      - Sets: notes/python/python-sets.md
      - Tuples: notes/python/python-tuples.md
      - Dictionaries: notes/python/python-dictionaries.md
      - Functions: notes/python/python-functions.md
      # - Object Oriented Programming: notes/python/python-OOP.md  
    - DSA:
      - Overview: notes/DSA/index.md
      - Basics: notes/DSA/DSA-Basics.md
      - Sorting Algorithms: notes/DSA/DSA-Algorithms.md
      - Data Structures Intro: notes/DSA/DSA-dsaintro.md
      - Stack & Queue: notes/DSA/DSA-Stack-queue.md
      - Linked List: notes/DSA/DSA-linked_list.md
    - Aptitude:
      - Numerical ability: notes/Aptitude/divisibility-rule.md
  - Projects:
    - Overview: projects/index.md
    - AI File search engine: projects/ai_file_search_assistant.md
    - Pneumonia Detection CNN: projects/Pneumonia-Detection-CNN.md
    - Expense Tracker: projects/expense-tracker.md
    - AI Web Scrapper: projects/AI-scrapper.md
    - VoteBloc: projects/votebloc.md
    - Flash cards: projects/flashcardsapp.md
    - Snake Xenzia: projects/Snake-Xenzia.md
    - Terminal projects: projects/terminal-projects.md    
